src/modules/frame/Header2.vue, src/modules/home/Banner.vue
Updated Page Layout, functionality buttons and  page responsiveness
=> Update: Banner Layout and Responsiveness

src/modules/frame/Header2.vue
Fixed header opening upon page load on small screens
=> Update: Fixed Header

src/modules/home/Banner.vue
Fixed gradient ratio on banner page
=> Update: Visual fix

src/modules/frame/Header2.vue
Fixed issue where mobile only header remains open on page navigate to login and register
=> Update: Fixed Issue on Header Display

src/modules/frame/Header2.vue, src/modules/home/Banner.vue, src/modules/home/Contact.vue, src/router/dev_routes/app.js
Added Contact.vue for contact page
Edited header, router to redirect to contact page
Fixed Visuals, Responsiveness
=> Added: Contact Page

src/modules/account/login.vue, src/modules/account/register.vue, src/modules/account/resetPassword.vue, src/modules/home/Contact.vue
Changed background element according to design changes
Updated Buttons layout
=> Update: Background Changes

src/modules/frame/Header.vue, src/modules/frame/Header2.vue
Fixed issue of blurred logo on mobile view
Added visual effects and changes on header at mobile view
=> Update: Visual, Layout Changes

src/modules/frame/Header.vue, src/modules/frame/Header2.vue, src/router/dev_routes/app.js
Updated header layout on mobile view
Added visual changes on both desktop and mobile headers
=> Update: Header Layout, Visuals

src/modules/frame/Header2.vue
=> Update: Header Visuals

src/modules/home/Banner.vue
Banner layout update for mobile and responsive view
=> Update: Layout

src/modules/frame/Header2.vue, src/modules/home/Contact.vue
Updated alignment of contact page
=> Update: Layout fixes

src/modules/account/settings.vue
=> settings update

src/modules/frame/Header.vue
- switched navbar colors
- centered user.type buttons
- changed dropdown to logout
=> navbar changes

src/modules/dashboard/ContentExpertDashboard.vue, src/modules/generic/table.vue
1. Visual update to list items
2. Removed some items
3. CSS changes
=> Update: Content Expert Visuals

src/modules/home/Contact.vue
1. Added template for Contact Us page email and message validation
=> Update: Contact Page Validation

api/app/Http/Controllers/PostController.php, api/database/migrations/2021_06_24_065354_update_posts_table.php, api/routes/web.php, src/modules/channels/AutomationSettings.vue, src/modules/channels/Branding.vue, src/modules/channels/index.vue, src/modules/dashboard/AdminDashboard.vue, src/modules/dashboard/ContentExpertDashboard.vue, src/modules/generic/preview.vue, src/modules/postManagement/Admin.vue, src/modules/postManagement/ContentExpert.vue, src/modules/subscriptions/user.vue
…e flag to true upon redirection from ADMIN DASHBOARD
=> update create posts migration, lacking payment and lack of setting the flag to true upon redirection from ADMIN DASHBOARD to post POST MANAGEMENT

src/modules/account/login.vue
=> login card

src/modules/account/settings.vue, src/modules/home/Contact.vue
1. CSS Changes on Contact.vue
2. Fixed red outline of Settings page for user
=> Update: CSS Changes

src/modules/home/Contact.vue
1. CSS Changes
2. Comment Changes
=> Update: Contact page

src/modules/account/login.vue, src/modules/account/register.vue, src/modules/account/settings.vue, src/modules/home/Contact.vue
1. Updated functionality 
2. CSS and Layout update
=> Update: Functionality 

src/modules/account/resetPassword.vue
1. Edited error message
2. Changed redirects on button press
=> Update: Forgot Password Page

src/modules/account/resetPassword.vue, src/modules/subscriptions/index.vue, src/modules/subscriptions/user.vue, src/modules/subscriptions/user2.vue, src/router/dev_routes/app.js
1. Added framework for subscription card
2. Route changes
3. Comment changes
=> Update: User Subscription page

src/modules/subscriptions/user2.vue
1. Added missing button in user subscription page
=> Update: Missing button

src/modules/subscriptions/plan.vue
1. Page redirect now fixed.
2. CSS changes.
=> Update: Missing page redirect

src/modules/subscriptions/plan.vue
1. Fixed broken subscription page card
2. CSS changes
3. Comment Changes
=> Update: Subscriptions

package-lock.json, package.json, src/modules/generic/searchField.vue, src/modules/postManagement/ContentExpert.vue
1. Added component that auto fills/search and return multiple industry tags on target_post table
2. Comment changes
=> Update: Autofill Industries

src/modules/generic/searchField.vue, src/modules/postManagement/AdminEdit.vue, src/modules/postManagement/ContentExpert.vue
1. Implemented in Content Expert page
2. Semi implementation on Admin page
3. Comment changes
4. CSS changes
=> Update: Search Field component

src/modules/account/components/account.vue, src/modules/account/components/address.vue, src/modules/account/components/cpass.vue, src/modules/account/components/profile.vue
1. Visual update (validation)
2. Code cleanup
3. CSS changes
=> Update: Settings & Settings Component

src/modules/account/components/address.vue, src/modules/account/components/profile.vue
1. Added watcher to watch and retrieve new db values without needing to refresh the page
2. Fixed missing value business name field
=> Update: Settings

src/modules/dashboard/AdminDashboard.vue, src/modules/postManagement/Admin.vue, src/modules/postManagement/UserHistory.vue
1. Visual Changes
2. CSS Changes
=> Update: Admin & User Dashboard

src/assets/style/theme.css, src/modules/postManagement/ContentExpert.vue, src/modules/postManagement/UserHistory.vue
1. Edited over all theme(theme.css) instead of every single page
=> Update: Theme

src/modules/account/components/address.vue, src/modules/generic/searchField.vue, src/modules/postManagement/AdminEdit.vue
1. Fixed missing and wrong error message displayed on Admin edit and when updating Account address
2. Comment changes
3. CSS Changes
=> Fixes: Post Management & Accounts

package-lock.json, package.json, src/modules/account/components/account.vue, src/modules/account/components/cpass.vue, src/modules/home/index.vue, src/modules/home/new/newBanner.vue, src/modules/postManagement/Admin.vue
=> Added: New Homepage banner

src/modules/frame/Content.vue, src/modules/frame/Footer2.vue, src/modules/home/new/Industry.vue
- added industry
- edited footer
=> changes to industry and footer

src/assets/style/theme.css, src/modules/frame/Header2.vue, src/modules/frame/old/oldFooter.vue, src/modules/frame/old/oldHeader.vue, src/modules/home/new/newBanner.vue
1. Updated homepage header and banner
2. Fixed wrong color on industry select hover 
3. CSS changes
=> Update: Theme, Homepage

src/modules/account/components/address.vue, src/modules/account/components/profile.vue
1. Altered verification method
2. Error message changed
=> Update: Account Settings

src/modules/account/components/profile.vue, src/modules/account/settings.vue, src/modules/home/new/newBanner.vue
1. Added functionality
2. CSS modification
3. Comment Changes
=> Update: New Landing page

src/modules/home/new/newBanner.vue
1. Design Changes
2. CSS Changes
3. Comment Changes
=> update: main page design

src/modules/home/new/newBanner.vue
1. Added dropdown functionality to rely on database data
=> Updated: Main page dropdown

src/modules/frame/Header.vue, src/modules/frame/Sidebar.vue
=> 'overlap_issue'

src/modules/account/components/address.vue, src/modules/account/components/profile.vue, src/modules/generic/preview.vue
1. Takes into account white spaces now
=> Post Preview Visuals

src/modules/postManagement/UserPreview.vue
- Preview now centered
- CSS changes
=> Update: Admin Preview
